export const IPC_CHANNELS = {
  vaultOpen: 'vault:open',
  vaultCreate: 'vault:create',
  vaultRestoreLast: 'vault:restore-last',
  vaultRunMigration: 'vault:run-migration',
  vaultMigrationReport: 'vault:migration-report',
  vaultListSaved: 'vault:list-saved',
  vaultSwitchSaved: 'vault:switch-saved',
  vaultToggleFavoriteSaved: 'vault:toggle-favorite-saved',
  vaultRemoveSaved: 'vault:remove-saved',
  desktopChooseDirectory: 'desktop:choose-directory',
  desktopChoosePath: 'desktop:choose-path',
  desktopOpenExternal: 'desktop:open-external',
  desktopOpenPath: 'desktop:open-path',
  desktopOpenWarpAtNotePath: 'desktop:open-warp-at-note-path',
  uiShowNativeMenu: 'ui:show-native-menu',
  uiReloadApp: 'ui:reload-app',
  listNotes: 'files:list-notes',
  listNoteTree: 'files:list-note-tree',
  filesTreeChanged: 'files:tree-changed',
  reminderClicked: 'reminders:clicked',
  listFleetingNotes: 'fleeting:list',
  createFleetingNote: 'fleeting:create',
  convertFleetingNote: 'fleeting:convert',
  removeFleetingNote: 'fleeting:remove',
  updateFleetingNote: 'fleeting:update',
  readNote: 'files:read-note',
  readNoteDocument: 'files:read-note-document',
  readExcalidrawFileDocument: 'files:read-excalidraw-file-document',
  writeNote: 'files:write-note',
  writeNoteDocument: 'files:write-note-document',
  writeExcalidrawFileDocument: 'files:write-excalidraw-file-document',
  createNote: 'files:create-note',
  createNoteAtPath: 'files:create-note-at-path',
  createExcalidrawFileAtPath: 'files:create-excalidraw-file-at-path',
  createNoteWithTags: 'files:create-note-with-tags',
  createFolder: 'files:create-folder',
  importNotes: 'files:import-notes',
  migrateBlockNoteNotes: 'files:migrate-blocknote-notes',
  migrateTaggedNoteBodyFrontmatter: 'files:migrate-tagged-note-body-frontmatter',
  migrateNoteImagePaths: 'files:migrate-note-image-paths',
  renameNote: 'files:rename-note',
  renamePath: 'files:rename-path',
  deleteNote: 'files:delete-note',
  deletePath: 'files:delete-path',
  deletePaths: 'files:delete-paths',
  exportNote: 'files:export-note',
  exportNotePdf: 'files:export-note-pdf',
  exportFolderPdf: 'files:export-folder-pdf',
  exportFolderMarkdown: 'files:export-folder-markdown',
  exportProjectContext: 'files:export-project-context',
  searchQuery: 'search:query',
  resourcesList: 'resources:list',
  resourcesAdd: 'resources:add',
  resourcesUpdate: 'resources:update',
  resourcesSetProjectNotebook: 'resources:set-project-notebook',
  resourcesDetachFromProject: 'resources:detach-from-project',
  resourcesRefresh: 'resources:refresh',
  resourcesLocate: 'resources:locate',
  resourcesPreview: 'resources:preview',
  resourcesRelate: 'resources:relate',
  resourcesProjectContext: 'resources:project-context',
  resourcesOpen: 'resources:open',
  resourcesReveal: 'resources:reveal',
  resourcesPreviewWrite: 'resources:preview-write',
  resourcesApplyWrite: 'resources:apply-write',
  resourcesWriteAudit: 'resources:write-audit',
  resourcesDriveStartAuthorization: 'resources:drive-start-authorization',
  resourcesDriveCompleteAuthorization: 'resources:drive-complete-authorization',
  resourcesDriveListFiles: 'resources:drive-list-files',
  resourcesDriveAttach: 'resources:drive-attach',
  resourcesDriveRefresh: 'resources:drive-refresh',
  resourcesDriveDisconnect: 'resources:drive-disconnect',
  aiCompleteNote: 'ai:complete-note',
  agentChatSendMessage: 'agent-chat:send-message',
  agentChatCancel: 'agent-chat:cancel',
  agentChatListSessions: 'agent-chat:list-sessions',
  agentChatSaveSession: 'agent-chat:save-session',
  agentChatDeleteSession: 'agent-chat:delete-session',
  agentChatApproveTool: 'agent-chat:approve-tool',
  agentChatEvent: 'agent-chat:event',
  excalidrawListSessions: 'excalidraw:list-sessions',
  excalidrawSaveSession: 'excalidraw:save-session',
  excalidrawDeleteSession: 'excalidraw:delete-session',
  excalidrawImportLegacySessions: 'excalidraw:import-legacy-sessions',
  agentHistoryListRuns: 'agent-history:list-runs',
  appErrorEvent: 'app:error-event',
  importAttachment: 'attachments:import',
  importAttachmentFromBuffer: 'attachments:import-from-buffer',
  settingsGet: 'settings:get',
  settingsUpdate: 'settings:update',
  credentialStatus: 'credentials:status',
  credentialSet: 'credentials:set',
  credentialDelete: 'credentials:delete',
  pythonListCondaEnvironments: 'python:list-conda-environments',
  pythonChooseCondaExecutable: 'python:choose-conda-executable',
  createProject: 'projects:create',
  selectProject: 'projects:select',
  updateProject: 'projects:update',
  setProjectState: 'projects:set-state',
  setProjectFavorite: 'projects:set-favorite',
  deleteProject: 'projects:delete',
  createProjectMilestone: 'projects:milestones:create',
  updateProjectMilestone: 'projects:milestones:update',
  reorderProjectMilestones: 'projects:milestones:reorder',
  deleteProjectMilestone: 'projects:milestones:delete',
  createProjectUpdate: 'projects:updates:create',
  updateProjectUpdate: 'projects:updates:update',
  deleteProjectUpdate: 'projects:updates:delete',
  createTask: 'tasks:create',
  historyUndo: 'history:undo',
  historyRedo: 'history:redo',
  historyStatus: 'history:status'
} as const

export const SCHEDULE_CHANNELS = {
  listJobs: 'schedule:list-jobs',
  saveJob: 'schedule:save-job',
  deleteJob: 'schedule:delete-job',
  runNow: 'schedule:run-now',
  cancelRun: 'schedule:cancel-run',
  listRuns: 'schedule:list-runs',
  applyActions: 'schedule:apply-actions',
  dismissRun: 'schedule:dismiss-run',
  listSecrets: 'schedule:list-secrets',
  saveSecret: 'schedule:save-secret',
  deleteSecret: 'schedule:delete-secret'
} as const

export const WEEKLY_PLAN_CHANNELS = {
  getState: 'weeklyPlan:get-state',
  createWeek: 'weeklyPlan:create-week',
  updateWeek: 'weeklyPlan:update-week',
  deleteWeek: 'weeklyPlan:delete-week',
  addPriority: 'weeklyPlan:add-priority',
  updatePriority: 'weeklyPlan:update-priority',
  deletePriority: 'weeklyPlan:delete-priority',
  reorderPriorities: 'weeklyPlan:reorder-priorities',
  upsertReview: 'weeklyPlan:upsert-review'
} as const

export const SUBSCRIPTION_CHANNELS = {
  list: 'subscriptions:list',
  get: 'subscriptions:get',
  create: 'subscriptions:create',
  update: 'subscriptions:update',
  delete: 'subscriptions:delete',
  archive: 'subscriptions:archive',
  addPayment: 'subscriptions:add-payment',
  getAnalytics: 'subscriptions:get-analytics'
} as const

export const CALENDAR_CHANNELS = {
  getState: 'calendar:get-state',
  startGoogleAuthorization: 'calendar:start-google-authorization',
  completeGoogleAuthorization: 'calendar:complete-google-authorization',
  cancelGoogleAuthorization: 'calendar:cancel-google-authorization',
  selectGoogleCalendars: 'calendar:select-google-calendars',
  syncGoogleConnection: 'calendar:sync-google-connection',
  createLocalEvent: 'calendar:create-local-event',
  updateLocalEvent: 'calendar:update-local-event',
  linkTaskToEvent: 'calendar:link-task-to-event',
  unlinkTaskFromEvent: 'calendar:unlink-task-from-event',
  deleteLocalCache: 'calendar:delete-local-cache',
  disconnectGoogleConnection: 'calendar:disconnect-google-connection',
  revokeGoogleConnection: 'calendar:revoke-google-connection'
} as const

export const AGENT_TOOL_CHANNELS = {
  invoke: 'agentTools:invoke'
} as const
